// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/sidebar/SideBar";
import SubSidebar from "@/components/layout/SubSideBar";
import Avatar from '@mui/material/Avatar';
import MainLogo from "@/components/logo/MainLogo";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <div className="flex flex-1 flex-col relative">
            <header className="sm:w-50 bg-black z-50 text-white p-4 fixed top-0 left-0 right-0 h-19 flex justify-between header_main_layout">
              <MainLogo />
              <Avatar
                className="mr-10"
                alt="Remy Sharp"
                src="https://static.vecteezy.com/system/resources/previews/018/765/757/original/user-profile-icon-in-flat-style-member-avatar-illustration-on-isolated-background-human-permission-sign-business-concept-vector.jpg"
                sx={{ width: 24, height: 24 }} />
            </header>
            <main className="flex-1 flex body_main_layout">
              <div className=" primary_color fixed top-0 left-0 bottom-0">
                <SideBar />
              </div>
              <div className="sub_side flex-0 ml-20 fixed top-10 bottom-0">
                <SubSidebar />
              </div>
              <div className="flex-1 ml-80 w-96">{children}</div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
