import React from "react";
import Settings from "./Settings";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "BitStorm",
    template: "%s | BitStorm",
  },
  description: "Generated by create next app",
};
export default function page() {
  return (
    <>
      <Settings />
    </>
  );
}
